import os

C_DIR = os.path.abspath(os.path.dirname(__file__))
DATA_DIR = "%s/data" % C_DIR
TMP_DIR = "%s/tmpOut" % C_DIR
FIG_DIR = "%s/figs" % C_DIR
LOG_DIR = "%s/logs" % C_DIR
OUTPUT_DIR = "%s/res" % C_DIR

DRUGBANK_ATC_INCHI = "%s/DrugBank/ATC_2_Inchikeys.txt" % DATA_DIR
PPI_FILE = "%s/HPRD/PPI_UNIPROT.txt" % DATA_DIR
PUBCHEM_FILE = "%s/PubChem/Inchikey2ProfileFilled.dat" % DATA_DIR
BINDINGDB_EXTENDED = "%s/DrugBank/BindingDTB" % DATA_DIR
DRUGBANK_INCHI_PROTEIN = "%s/DrugBank/DRUBBANK_INCHIKEY_2_PROTEIN.dat" % DATA_DIR
KEGG_UNIPROT_PATHWAY_MAPPING_PATH = "%s/KEGG/uniprot_2_pathway.txt" % DATA_DIR
SMILE2GRAPH = "%s/DrugBank/SMILDE2GRAPH.dat" % DATA_DIR

DRUGSCOM_DRUG_ID_RAW = "%s/DRUGSCOM/RawDrugWebText.dat" % DATA_DIR
DRUGSCOM_DRUG_ID_WEB = "%s/DRUGSCOM/DrugWebId.txt" % DATA_DIR

DDI_DIR = "%s/DDI" % DATA_DIR
PATH_TWOSIDES_A = "%s/TWOSIDES_ALL.txt" % DDI_DIR
PATH_TWOSIDES_C5 = "%s/TWOSIDES_C5.txt" % DDI_DIR
PATH_JADERDDI = "%s/JADERDDI.txt" % DDI_DIR
PATH_CADDDI = "%s/CADDDI.txt" % DDI_DIR
MONO_ADR_FILE = "%s/MONOADR.txt" % DDI_DIR

ID2NamePath_TWOSIDE = "%s/TWOSIDES/Id2Name" % TMP_DIR
EMBEDDING_PREX = "%s/Embeding_" % TMP_DIR

EMBEDDING_PREX2 = "%s/Res/Embeding_" % TMP_DIR

TORCH_SEED = int('1100110011010100111011011010011', 2)

OPTIMIZER = "Adam"

FORCE_SKIP_OPTIONS = False
FORCE_CPU = False



K_FOLD = 20

N_ITER = 3000
ITER_DB = 100





PROTEIN_FEATURE = True

PRINT_DB = True



D_PREF = ""

MAX_R_ADR = 1000
MAX_R_DRUG = 600
ADR_OFFSET = 0
SAMPLE_NEG = 800


MODEL = ""

ON_REAL = True
P_SYN = 1.0
DEG_NORM = True
KSPACE = False
ONE_HOT = False
ON_W = True
LEARN_WEIGHT_IN = False
LEARN_WEIGHT_LAST = True

N_SGD = 80

N_LAYER = 1
L_W = 0.1
LAMBDA_R = 0.1
R_TYPE = "L1"


LAYER_WEIGHT = True
EMBEDDING_SIZE = 50

GPU_DEVICE = "cuda:1"

NUM_LISTI_WORKER = 10
PATHWAY = False
N_DATA_WORKER = 5

N_SEC = 20
S_KFOLD = 5
VISUAL = False
EXPORT_TOP_NEG = False


